### ISSUE TITLE
Enhancement request: ability to add lips to the top

### ISSUE THREAD

**Issue by rspilhaus** [Harem-Rose/Magnet-Base-Maker#1]
First, let me say - AMAZING tool. 

Would be pretty great if we could add a defined "lip" to the top of the base (for things like resin pours, etc). 

Anyhow, feel free to delete this if you're not doing any more work on this, and thanks for the tool!

**Comment by Harem-Rose** [comment]
Hey there, I am glad you like it. I want to respond directly to your
statements

1) You can probably get away with a "lip" using multibasing.
    A) Set MakeMultiBase = 1
    B) Set MultiBaseCount = 0
    C) Set MultiBaseAddCenter =  1
    D) Set MultiBaseWidth to be about the width of the top of the base
minus a few mm (This might take some finangling if you are using
"traditional" edge style
    E) Set MultiBaseDepth to be the desired depth. The tool will
automatically thicken the base to accommodate
    F) Set MultiBaseMagnetWidth = 0
    G) Set MultiBaseMagnetDepth = 0

2) I do plan on adding more work to the tool. I am not 100% on if I will
add a direct tool to add a lip since you can emulate that in a way with the
multibasing, but I'll consider it.
3) I am in the middle of a decision-making-process on if the tool will be
moved off of GitHub before the start of October. If it is moved, I will
leave a link to its new location.

I appreciate your interest in the tool!

**Comment by rspilhaus** [comment]
Wonderful - thanks!
